move cache creation in __init__.py to func
causes an error in testing, and is generally
better design:

/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/pathlib.py:1273: in mkdir
self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.local/share/url_metadata'